apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: example-provider-operator-clusterscopedresource-editor-role
rules:
- apiGroups:
  - resource.acme.com
  resources:
  - clusterscopedresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.acme.com
  resources:
  - clusterscopedresources/status
  verbs:
  - get
