# permissions for end users to view clusterscopedresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterscopedresource-viewer-role
rules:
- apiGroups:
  - resource.acme.com
  resources:
  - clusterscopedresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resource.acme.com
  resources:
  - clusterscopedresources/status
  verbs:
  - get
